# Generated by Django 4.0 on 2022-01-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
